_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.3
            "6": 4.34.0
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
